config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, :dependent => :destroy, :inverse_of => :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, :inverse_of => :room_messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:email, :username])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
    before_action :load_entities

    def create
        @room_message = RoomMessage.create(:user => current_user, :room => @room, :message => params.dig(:room_message, :message))
    end

    private

    def load_entities
        @room = Room.find(params.dig(:room_message, :room_id))
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(permitted_params)

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new(:room => @room)
    @room_messages = @room.room_messages.includes(:user)
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_params)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  private

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all",  "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render :partial => 'shared/navigation_bar' %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
    <%= link_to new_room_path, class: "btn btn-primary" do %>
    Create a room
    <% end %>
</div>

<% if @rooms.present? %>
    <nav class="nav flex-column">
    <% @rooms.each do |room| %>
        <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
    <% end %>
    </nav>
<% else %>
    <div class="text-muted">
    The are no rooms
    </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a room
      <% end %>
    </div>

    <% if @rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to Chatter!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
   <%= @room.name %> 
</h1>

<div class="row">
    <div class="col-12 col-md-3">
        <%= render partial: 'rooms' %>
    </div>

    <div class="col">
        <div class="chat">
            <% @room_messages.each do |room_message| %>
                <div class="chat-message-container">
                    <div class="row no-gutters">
                        <div class="col-auto text-center">
                        <img src="<%= gravatar_url(room_message.user) %>" class="avatar" alt="">
                        </div>

                        <div class="col">
                        <div class="message-content">
                            <p class="mb-1">
                            <%= room_message.message %>
                            </p>

                            <div class="text-right">
                            <small>
                                <%= room_message.created_at %>
                            </small>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
            <% end %>
        </div>

        <%= simple_form_for @room_message, :remote => true do |form| %>
            <div class="input-group mb-3">
                <%= form.input :message, :as => :string, :wrapper => false, :label => false, :input_html => { :class => 'chat-input' } %>
                <div class="input-group-append">
                    <%= form.submit "Send", :class => 'btn btn-primary chat-input' %>
                </div>
            </div>

            <%= form.input :room_id, :as => :hidden %>
        <% end %>
    </div>
</div>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="#">Chatter</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_user) %>">
        <%= current_user.username %>
      </a>


        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'logout' %>
    </div>
  <% end %>
</nav>